#!/bin/bash

# Symphony No.5 Command Line Tool
# Original Homepage: http://github.com/firegoby/symphonyno5.sh.git
# Original Author: Chris Batchelor (http://firegoby.com/)
# License: Unlicense (http://unlicense.org)

# Symphony CMS 2.3.4

usage() {
  scriptname=`basename $0`
  echo "Symphony No.5 使用方法"
  echo ""
  echo "建立新開發專案"
  echo "    $scriptname new projectname"
  echo ""
  echo "根據 extensions.csv 更新/安裝 git submodules"
  echo "    $scriptname extensions"
  echo ""
  echo "設置 manifest 與 workspace 目錄的檔案權限"
  echo "    $scriptname setperms 0775 0664"
  echo ""
  echo "修復權限 - 根據 manifest/config.php 設置 manifest 與 workspace 的檔案權限"
  echo "    $scriptname fixperms"
}

verifySymphonyRoot() {
  if [ ! -e index.php -a ! -d symphony ]
  then
    echo "錯誤： 似乎您並不在一個 Symphony 專案的根目錄下！指令終止。"
    exit 1
  fi
}

extensions() {
  verifySymphonyRoot
  filename="extensions.csv"
  if [ -f $filename ] 
  then
    while IFS="," read one two
    do
      git submodule add "$one" "$two"
    done < "$filename"
    git submodule update --init
  else
    echo "錯誤：找不到 extensions.csv 檔案！指令終止。"
  fi
}


setperms() {
  verifySymphonyRoot
  echo "設定 manifest 目錄的權限為 $1"
  find manifest.* -type d -exec chmod $1 {} \;
  echo "設定 workspace 目錄的權限為 $1"
  find workspace -type d -exec chmod $1 {} \;
  echo "設定 manifest 檔案的權限為 $2"
  find manifest.* -type f -exec chmod $2 {} \;
  echo "設定 workspace 檔案的權限為 $2"
  find workspace -type f -exec chmod $2 {} \;
}

fixperms() {
  verifySymphonyRoot
  fileperms=`awk '/file/ {getline;print substr($0, length-5, 4)}' manifest/config.php`
  dirperms=`awk '/directory/ {getline;print substr($0, length-5, 4)}' manifest/config.php`
  setperms $dirperms $fileperms
}

new(){
  project="$1"
  read -p "已經新建 MySQL 資料庫並設置好網站伺服器了嗎？(y/n)? " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo ""
    echo "建立新的 Symphony 專案： $project"
    git clone -b master --depth 1 git://github.com/wastemobile/symphonyno5.git $project
    cd $project
    echo "移除安裝用的遠端倉儲"
    rm -rf .git
    echo "調整一下權限方便安裝"
    chmod 777 symphony .
    chmod -R 777 workspace
    echo "重新建立起始倉儲"
    git init
    echo "根據 extensions.csv 的外掛清單依序檢查安裝"
    extensions
    echo "建立 manifest.dev 的目錄連結"
    ln -s manifest.dev manifest
    echo "*********************************"
    echo "請使用瀏覽器開啓 http://yourdomain.com/install 並根據指示完成後續的安裝步驟"
    echo "當您成功安裝並登入後台時，請回到這裡繼續後面的操作..."
    read -p "繼續嗎？ (y/n) " -n 1
    if [[ $REPLY =~ ^[Nn]$ ]]
    then
      echo ""
      echo "放棄安裝"
      exit 1
    else
      echo ""
      read -p "您想要移除 Symphony 的說明與版權檔案嗎？ (y/n) " -n 1
      if [[ $REPLY =~ ^[Yy]$ ]]
      then
        echo ""
        echo "移除 Symphony 的說明與版權檔案..."
        rm README.* LICENSE.*
      fi
      if [ ! -f manifest.prod/config.php ]
      then
        echo "拷貝 manifest.dev/config.php 到 manifest.prod 目錄"
        cp manifest.dev/config.php manifest.prod/config.php
      fi
      if [ -d install ]
      then
        echo "移除安裝檔案"
        rm -rf install
      fi
      fileperms=`awk '/file/ {getline;print substr($0, length-5, 4)}' manifest/config.php`
      dirperms=`awk '/directory/ {getline;print substr($0, length-5, 4)}' manifest/config.php`
      echo "設定根目錄的權限為 $dirperms"
      chmod $dirperms .
      echo "設定根目錄檔案的權限為 $fileperms"
      find . -type f -maxdepth 1 -exec chmod $fileperms {} \;
      echo "設定 Symphony 目錄的權限為 $dirperms"
      find symphony -type d -exec chmod $dirperms {} \;
      echo "設定 Symphony 檔案的權限為 $fileperms"
      find symphony -type f -exec chmod $fileperms {} \;
      fixperms
      echo "替專案設置 Git 初始化"
      git add .
      echo "建立第一個提交"
      git commit -m "Initial commit"
      echo "建立並切換到 'develop' 分支（根據分支 'master'）"
      git checkout -b develop
      echo "*********************************"
      echo ""
      echo "恭喜！你的 Symphony 新專案： '$project' 已經成功建立！"
      echo ""
      echo "'cd $project' 切換到專案目錄開始工作吧..."
      exit 0
    fi
  else
    echo ""
    echo "指令繼續之前，您必須先..."
    echo "* 建立所需的 MySQL 資料庫 (請使用 utf-8 編碼)"
    echo "* 建立管理 MySQL 資料庫的管理員名稱與密碼"
    echo "* 設定網站伺服器（通常是 Apache）運行您的網站 `pwd`/$project"
  fi
}

cmd=$1
case $cmd in
        new) new $2;;
 extensions) extensions;;
   setperms) setperms $2 $3;;
   fixperms) fixperms;;
          *) usage
esac
